import DesktopLayout from "@/components/desktop-layout";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
      >
        <div className="flex max-w-[60rem] mx-auto gap-6 justify-between">
          <div className="hidden lg:block w-full md:max-w-[390px] max-auto h-screen">
            <DesktopLayout />
          </div>
          <div className="relative w-full sm:max-w-[390px] mx-auto lg:mx-0 h-screen lg:border">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
